// --- COMMUNITY TIERS ---
export const sTierItems = [
    "Sun", "Magma", "Hemorrhage", "Overgrowth", "Maggot", 
    "Flash", "Flicker", "Black Hole", "Glacier", "Cornucopia"
];

// --- CHARACTERS ---
export const charactersDB = [
    { name: "The Warrior", ball: "Bleed", img: "https://ballxpit.wiki.gg/images/The_Warrior.png", desc: "No special quirks." },
    { name: "The Itchy Finger", ball: "Burn", img: "https://ballxpit.wiki.gg/images/The_Itchy_Finger.png", desc: "Shoots twice as fast, scattered aim." },
    { name: "The Repentant", ball: "Freeze", img: "https://ballxpit.wiki.gg/images/The_Repentant.png", desc: "Balls deal more dmg on bounce, hurt enemies on return." },
    { name: "The Cohabitants", ball: "Brood Mother", img: "https://ballxpit.wiki.gg/images/The_Cohabitants.png", desc: "Launches mirror copy of every ball." },
    { name: "The Cogitator", ball: "Laser (Vertical)", img: "https://ballxpit.wiki.gg/images/The_Cogitator.png", desc: "Automatically chooses upgrades." },
    { name: "The Embedded", ball: "Poison", img: "https://ballxpit.wiki.gg/images/The_Embedded.png", desc: "Balls pierce enemies until hitting a wall." },
    { name: "The Shade", ball: "Dark", img: "https://ballxpit.wiki.gg/images/The_Shade.png", desc: "Balls shoot from the back. +10% Crit." },
    { name: "The Shieldbearer", ball: "Iron", img: "https://ballxpit.wiki.gg/images/The_Shieldbearer.png", desc: "Holds a shield that bounces balls back." },
    { name: "The Spendthrift", ball: "Vampire", img: "https://ballxpit.wiki.gg/images/The_Spendthrift.png", desc: "Shoots all balls at same time in arc." },
    { name: "The Juggler", ball: "Lightning", img: "https://ballxpit.wiki.gg/images/The_Juggler.png", desc: "Lobs balls into the air." },
    { name: "The Empty Nester", ball: "Ghost", img: "https://ballxpit.wiki.gg/images/The_Empty_Nester.png", desc: "No baby balls. Shoots multiple instances of special ball." },
    { name: "The Flagellant", ball: "Egg Sac", img: "https://ballxpit.wiki.gg/images/The_Flagellant.png", desc: "Balls bounce normally off bottom." },
    { name: "The Makeshift Sisyphus", ball: "Earthquake", img: "https://ballxpit.wiki.gg/images/The_Makeshift_Sisyphus.png", desc: "No direct hit dmg. 4x AOE/Status dmg." },
    { name: "The Physicist", ball: "Light", img: "https://ballxpit.wiki.gg/images/The_Physicist.png", desc: "Balls affected by gravity towards back." },
    { name: "The Tactician", ball: "Iron", img: "https://ballxpit.wiki.gg/images/The_Tactician.png", desc: "Battles become turn-based." },
    { name: "The Radical", ball: "Wind", img: "https://ballxpit.wiki.gg/images/The_Radical.png", desc: "Plays automatically." },
    { name: "The Falconer", ball: "Lightning", img: "https://ballxpit.wiki.gg/images/The_Falconer.png", desc: "Balls shot from falcons on sides." },
    { name: "The Carouser", ball: "Charm", img: "https://ballxpit.wiki.gg/images/The_Carouser.png", desc: "Balls orbit on return." },
    { name: "The False Messiah", ball: "Bleed", img: "https://ballxpit.wiki.gg/images/The_False_Messiah.png", desc: "Twitch Integration character." }
];

// --- BALLS ---
export const ballsDB = [
    { name: "Bleed", img: "https://ballxpit.wiki.gg/images/Bleed.png" },
    { name: "Brood Mother", img: "https://ballxpit.wiki.gg/images/Brood_Mother.png" },
    { name: "Burn", img: "https://ballxpit.wiki.gg/images/Burn.png" },
    { name: "Cell", img: "https://ballxpit.wiki.gg/images/Cell.png" },
    { name: "Charm", img: "https://ballxpit.wiki.gg/images/Charm.png" },
    { name: "Dark", img: "https://ballxpit.wiki.gg/images/Dark.png" },
    { name: "Earthquake", img: "https://ballxpit.wiki.gg/images/Earthquake.png" },
    { name: "Egg Sac", img: "https://ballxpit.wiki.gg/images/Egg_Sac.png" },
    { name: "Freeze", img: "https://ballxpit.wiki.gg/images/Freeze.png" },
    { name: "Ghost", img: "https://ballxpit.wiki.gg/images/Ghost.png" },
    { name: "Iron", img: "https://ballxpit.wiki.gg/images/Iron.png" },
    { name: "Laser (Horizontal)", img: "https://ballxpit.wiki.gg/images/Laser_%28Horizontal%29.png" },
    { name: "Laser (Vertical)", img: "https://ballxpit.wiki.gg/images/Laser_%28Vertical%29.png" },
    { name: "Light", img: "https://ballxpit.wiki.gg/images/Light.png" },
    { name: "Lightning", img: "https://ballxpit.wiki.gg/images/Lightning.png" },
    { name: "Stone", img: "https://ballxpit.wiki.gg/images/Stone_%28Ball%29.png" },
    { name: "Poison", img: "https://ballxpit.wiki.gg/images/Poison.png" },
    { name: "Vampire", img: "https://ballxpit.wiki.gg/images/Vampire.png" },
    { name: "Wind", img: "https://ballxpit.wiki.gg/images/Wind.png" },
    { name: "Assassin", img: "https://ballxpit.wiki.gg/images/Assassin.png" },
    { name: "Banished Flame", img: "https://ballxpit.wiki.gg/images/Banished_Flame.png" },
    { name: "Berserk", img: "https://ballxpit.wiki.gg/images/Berserk.png" },
    { name: "Black Hole", img: "https://ballxpit.wiki.gg/images/Black_Hole.png" },
    { name: "Blizzard", img: "https://ballxpit.wiki.gg/images/Blizzard.png" },
    { name: "Bomb", img: "https://ballxpit.wiki.gg/images/Bomb.png" },
    { name: "Brimstone", img: "https://ballxpit.wiki.gg/images/Brimstone.png" },
    { name: "Catapult", img: "https://ballxpit.wiki.gg/images/Catapult.png" },
    { name: "Fireworks", img: "https://ballxpit.wiki.gg/images/Fireworks.png" },
    { name: "Flash", img: "https://ballxpit.wiki.gg/images/Flash.png" },
    { name: "Flicker", img: "https://ballxpit.wiki.gg/images/Flicker.png" },
    { name: "Freeze Ray", img: "https://ballxpit.wiki.gg/images/Freeze_Ray.png" },
    { name: "Frozen Flame", img: "https://ballxpit.wiki.gg/images/Frozen_Flame.png" },
    { name: "Glacier", img: "https://ballxpit.wiki.gg/images/Glacier.png" },
    { name: "Hemorrhage", img: "https://ballxpit.wiki.gg/images/Hemorrhage.png" },
    { name: "Holy Laser", img: "https://ballxpit.wiki.gg/images/Holy_Laser.png" },
    { name: "Incubus", img: "https://ballxpit.wiki.gg/images/Incubus.png" },
    { name: "Inferno", img: "https://ballxpit.wiki.gg/images/Inferno.png" },
    { name: "Landslide", img: "https://ballxpit.wiki.gg/images/Landslide.png" },
    { name: "Laser Beam", img: "https://ballxpit.wiki.gg/images/Laser_Beam.png" },
    { name: "Laser Cutter", img: "https://ballxpit.wiki.gg/images/Laser_Cutter.png" },
    { name: "Leech", img: "https://ballxpit.wiki.gg/images/Leech.png" },
    { name: "Lightning Rod", img: "https://ballxpit.wiki.gg/images/Lightning_Rod.png" },
    { name: "Lovestruck", img: "https://ballxpit.wiki.gg/images/Lovestruck.png" },
    { name: "Maggot", img: "https://ballxpit.wiki.gg/images/Maggot.png" },
    { name: "Magma", img: "https://ballxpit.wiki.gg/images/Magma.png" },
    { name: "Mosquito King", img: "https://ballxpit.wiki.gg/images/Mosquito_King.png" },
    { name: "Mosquito Swarm", img: "https://ballxpit.wiki.gg/images/Mosquito_Swarm.png" },
    { name: "Nosferatu", img: "https://ballxpit.wiki.gg/images/Nosferatu.png" },
    { name: "Noxious", img: "https://ballxpit.wiki.gg/images/Noxious.png" },
    { name: "Nuclear Bomb", img: "https://ballxpit.wiki.gg/images/Nuclear_Bomb.png" },
    { name: "Overgrowth", img: "https://ballxpit.wiki.gg/images/Overgrowth.png" },
    { name: "Phantom", img: "https://ballxpit.wiki.gg/images/Phantom.png" },
    { name: "Radiation Beam", img: "https://ballxpit.wiki.gg/images/Radiation_Beam.png" },
    { name: "Sacrifice", img: "https://ballxpit.wiki.gg/images/Sacrifice.png" },
    { name: "Sandstorm", img: "https://ballxpit.wiki.gg/images/Sandstorm.png" },
    { name: "Satan", img: "https://ballxpit.wiki.gg/images/Satan.png" },
    { name: "Shotgun", img: "https://ballxpit.wiki.gg/images/Shotgun.png" },
    { name: "Soul Sucker", img: "https://ballxpit.wiki.gg/images/Soul_Sucker.png" },
    { name: "Spider Queen", img: "https://ballxpit.wiki.gg/images/Spider_Queen.png" },
    { name: "Steel", img: "https://ballxpit.wiki.gg/images/Steel.png" },
    { name: "Storm", img: "https://ballxpit.wiki.gg/images/Storm.png" },
    { name: "Succubus", img: "https://ballxpit.wiki.gg/images/Succubus.png" },
    { name: "Sun", img: "https://ballxpit.wiki.gg/images/Sun.png" },
    { name: "Swamp", img: "https://ballxpit.wiki.gg/images/Swamp.png" },
    { name: "Vampire Lord", img: "https://ballxpit.wiki.gg/images/Vampire_Lord.png" },
    { name: "Virus", img: "https://ballxpit.wiki.gg/images/Virus.png" },
    { name: "Voluptuous Egg Sac", img: "https://ballxpit.wiki.gg/images/Voluptuous_Egg_Sac.png" },
    { name: "Wraith", img: "https://ballxpit.wiki.gg/images/Wraith.png" }
];

// --- PASSIVES ---
export const passivesDB = [
    { name: "Archer's Effigy", img: "https://ballxpit.wiki.gg/images/Archer%27s_Effigy.png" },
    { name: "Artificial Heart", img: "https://ballxpit.wiki.gg/images/Artificial_Heart.png" },
    { name: "Baby Rattle", img: "https://ballxpit.wiki.gg/images/Baby_Rattle.png" },
    { name: "Bandage Roll", img: "https://ballxpit.wiki.gg/images/Bandage_Roll.png" },
    { name: "Bottled Tornado", img: "https://ballxpit.wiki.gg/images/Bottled_Tornado.png" },
    { name: "Breastplate", img: "https://ballxpit.wiki.gg/images/Breastplate.png" },
    { name: "Crown of Thorns", img: "https://ballxpit.wiki.gg/images/Crown_of_Thorns.png" },
    { name: "Cursed Elixir", img: "https://ballxpit.wiki.gg/images/Cursed_Elixir.png" },
    { name: "Deadeye's Amulet", img: "https://ballxpit.wiki.gg/images/Deadeye%27s_Amulet.png" },
    { name: "Diamond Hilted Dagger", img: "https://ballxpit.wiki.gg/images/Diamond_Hilted_Dagger.png" },
    { name: "Dynamite", img: "https://ballxpit.wiki.gg/images/Dynamite.png" },
    { name: "Emerald Hilted Dagger", img: "https://ballxpit.wiki.gg/images/Emerald_Hilted_Dagger.png" },
    { name: "Ethereal Cloak", img: "https://ballxpit.wiki.gg/images/Ethereal_Cloak.png" },
    { name: "Everflowing Goblet", img: "https://ballxpit.wiki.gg/images/Everflowing_Goblet.png" },
    { name: "Eye of the Beholder", img: "https://ballxpit.wiki.gg/images/Eye_of_the_Beholder.png" },
    { name: "Fleet Feet", img: "https://ballxpit.wiki.gg/images/Fleet_Feet.png" },
    { name: "Frozen Spike", img: "https://ballxpit.wiki.gg/images/Frozen_Spike.png" },
    { name: "Gemspring", img: "https://ballxpit.wiki.gg/images/Gemspring.png" },
    { name: "Ghostly Corset", img: "https://ballxpit.wiki.gg/images/Ghostly_Corset.png" },
    { name: "Ghostly Shield", img: "https://ballxpit.wiki.gg/images/Ghostly_Shield.png" },
    { name: "Golden Bull", img: "https://ballxpit.wiki.gg/images/Golden_Bull.png" },
    { name: "Hand Fan", img: "https://ballxpit.wiki.gg/images/Hand_Fan.png" },
    { name: "Hand Mirror", img: "https://ballxpit.wiki.gg/images/Hand_Mirror.png" },
    { name: "Healer's Effigy", img: "https://ballxpit.wiki.gg/images/Healer%27s_Effigy.png" },
    { name: "Hourglass", img: "https://ballxpit.wiki.gg/images/Hourglass.png" },
    { name: "Iron Onesie", img: "https://ballxpit.wiki.gg/images/Iron_Onesie.png" },
    { name: "Kiss of Death", img: "https://ballxpit.wiki.gg/images/Kiss_of_Death.png" },
    { name: "Lover's Quiver", img: "https://ballxpit.wiki.gg/images/Lover%27s_Quiver.png" },
    { name: "Magic Staff", img: "https://ballxpit.wiki.gg/images/Magic_Staff.png" },
    { name: "Magnet", img: "https://ballxpit.wiki.gg/images/Magnet.png" },
    { name: "Midnight Oil", img: "https://ballxpit.wiki.gg/images/Midnight_Oil.png" },
    { name: "Pressure Valve", img: "https://ballxpit.wiki.gg/images/Pressure_Valve.png" },
    { name: "Protective Charm", img: "https://ballxpit.wiki.gg/images/Protective_Charm.png" },
    { name: "Radiant Feather", img: "https://ballxpit.wiki.gg/images/Radiant_Feather.png" },
    { name: "Reacher's Spear", img: "https://ballxpit.wiki.gg/images/Reacher%27s_Spear.png" },
    { name: "Rubber Headband", img: "https://ballxpit.wiki.gg/images/Rubber_Headband.png" },
    { name: "Ruby Hilted Dagger", img: "https://ballxpit.wiki.gg/images/Ruby_Hilted_Dagger.png" },
    { name: "Sapphire Hilted Dagger", img: "https://ballxpit.wiki.gg/images/Sapphire_Hilted_Dagger.png" },
    { name: "Shortbow", img: "https://ballxpit.wiki.gg/images/Shortbow.png" },
    { name: "Silver Blindfold", img: "https://ballxpit.wiki.gg/images/Silver_Blindfold.png" },
    { name: "Silver Bullet", img: "https://ballxpit.wiki.gg/images/Silver_Bullet.png" },
    { name: "Slingshot", img: "https://ballxpit.wiki.gg/images/Slingshot.png" },
    { name: "Spiked Collar", img: "https://ballxpit.wiki.gg/images/Spiked_Collar.png" },
    { name: "Stone Effigy", img: "https://ballxpit.wiki.gg/images/Stone_Effigy.png" },
    { name: "Traitor's Cowl", img: "https://ballxpit.wiki.gg/images/Traitor%27s_Cowl.png" },
    { name: "Turret", img: "https://ballxpit.wiki.gg/images/Turret.png" },
    { name: "Upturned Hatchet", img: "https://ballxpit.wiki.gg/images/Upturned_Hatchet.png" },
    { name: "Vampiric Sword", img: "https://ballxpit.wiki.gg/images/Vampiric_Sword.png" },
    { name: "Voodoo Doll", img: "https://ballxpit.wiki.gg/images/Voodoo_Doll.png" },
    { name: "Wagon Wheel", img: "https://ballxpit.wiki.gg/images/Wagon_Wheel.png" },
    { name: "War Horn", img: "https://ballxpit.wiki.gg/images/War_Horn.png" },
    { name: "Wretched Onion", img: "https://ballxpit.wiki.gg/images/Wretched_Onion.png" },
    { name: "Cornucopia", img: "https://ballxpit.wiki.gg/images/Cornucopia.png" },
    { name: "Deadeye's Cross", img: "https://ballxpit.wiki.gg/images/Deadeye%27s_Cross.png" },
    { name: "Deadeye's Impaler", img: "https://ballxpit.wiki.gg/images/Deadeye%27s_Impaler.png" },
    { name: "Gracious Impaler", img: "https://ballxpit.wiki.gg/images/Gracious_Impaler.png" },
    { name: "Grotesque Artillery", img: "https://ballxpit.wiki.gg/images/Grotesque_Artillery.png" },
    { name: "Odiferous Shell", img: "https://ballxpit.wiki.gg/images/Odiferous_Shell.png" },
    { name: "Phantom Regalia", img: "https://ballxpit.wiki.gg/images/Phantom_Regalia.png" },
    { name: "Soul Reaver", img: "https://ballxpit.wiki.gg/images/Soul_Reaver.png" },
    { name: "Tormenters Mask", img: "https://ballxpit.wiki.gg/images/Tormenters_Mask.png" },
    { name: "Wings of the Anointed", img: "https://ballxpit.wiki.gg/images/Wings_of_the_Anointed.png" }
];

// --- META DATA ---
export const characterDuos = [
    {
        name: "The Cluster Bomb",
        tag: "SCREEN CLEAR",
        chars: ["The Juggler", "The Spendthrift"],
        desc: "Throws all balls as one giant cluster (Juggler) that detonates on impact (Spendthrift). Massive burst damage."
    },
    {
        name: "The Backline Shotgun",
        tag: "AFK FARM",
        chars: ["The Shade", "The Spendthrift"],
        desc: "Shots originate from behind enemies in a wide arc. Aim straight down and strafe. Melts waves instantly."
    },
    {
        name: "Infinite Swarm",
        tag: "LAG MACHINE",
        chars: ["The Cohabitants", "The Flagellant"],
        desc: "Maximum baby ball generation. Flagellant keeps balls in play, Cohabitants doubles them. Frame-drop levels of chaos."
    },
    {
        name: "Easy Mode",
        tag: "BOUNCY",
        chars: ["The Physicist", "The Repentant"],
        desc: "Physicist pulls balls down, Repentant adds damage per bounce. Extremely consistent and safe."
    },
    {
        name: "The Hemorrhage",
        tag: "BOSS KILLER",
        chars: ["The Warrior", "The Shieldbearer"],
        desc: "Starts with Bleed + Iron to rush Hemorrhage. Percentage-based damage shreds high HP bosses."
    },
    {
        name: "Piercing Boomerang",
        tag: "TECH",
        chars: ["The Repentant", "The Embedded"],
        desc: "Balls pierce enemies (Embedded) and return from back wall dealing dmg (Repentant). Great for clearing lines."
    },
    {
        name: "Earth Shaker",
        tag: "AOE",
        chars: ["The Juggler", "The Makeshift Sisyphus"],
        desc: "Lob explosive Earthquake balls directly into the center of enemy clusters. Bypasses Sisyphus's downside."
    }
];

export const metaBuilds = [
    { 
        name: "Black Hole Sun", 
        tag: "GOD TIER",
        desc: "Sun makes Black Hole apply to EVERYTHING on screen. Instant wipe for non-bosses.",
        core: ["Black Hole", "Sun"], 
        support: ["Cornucopia", "Ethereal Cloak"] 
    },
    { 
        name: "Bleed Flash", 
        tag: "BOSS MELTER",
        desc: "Hemorrhage cuts % Current HP. Flash spreads it instantly to bosses.", 
        core: ["Hemorrhage", "Flash"], 
        support: ["Gemspring", "Silver Bullet"] 
    },
    { 
        name: "Seeker Missiles", 
        tag: "SYNERGY",
        desc: "Mosquito Swarm x Nuclear Bomb turns nukes into homing missiles.", 
        core: ["Mosquito Swarm", "Nuclear Bomb"], 
        support: ["Maggot", "Midnight Oil"] 
    },
    { 
        name: "Immortal Turtle", 
        tag: "SURVIVAL",
        desc: "Succubus + Spider Queen generates infinite weak balls. Charmed enemies heal you forever.", 
        core: ["Succubus", "Spider Queen"], 
        support: ["Soul Reaver", "Phantom Regalia"] 
    }
];

export const evolutions = [
    { name: "Assassin", ingredients: ["Iron", "Ghost", "Dark"], logic: "Iron + (Ghost OR Dark)", desc: "Backstabs deal 30% bonus dmg." },
    { name: "Banished Flame", ingredients: ["Dark", "Burn"], logic: "Dark + Burn", desc: "Darkflame (DOT + Burst)." },
    { name: "Berserk", ingredients: ["Charm", "Burn", "Bleed"], logic: "Charm + (Bleed OR Burn)", desc: "Enemies attack adjacent units." },
    { name: "Black Hole", ingredients: ["Dark", "Sun"], logic: "Dark + Sun", desc: "Instantly kills first enemy." },
    { name: "Blizzard", ingredients: ["Freeze", "Lightning", "Wind"], logic: "Freeze + (Wind OR Lightning)", desc: "Freezes area for 0.8s." },
    { name: "Bomb", ingredients: ["Burn", "Iron"], logic: "Burn + Iron", desc: "Explodes for 150-300 AOE." },
    { name: "Brimstone", ingredients: ["Burn", "Poison", "Stone"], logic: "Burn + (Poison OR Stone)", desc: "Burn + Poison aura." },
    { name: "Catapult", ingredients: ["Stone", "Egg Sac"], logic: "Stone + Egg Sac", desc: "Launches stone baby balls." },
    { name: "Fireworks", ingredients: ["Burn", "Egg Sac"], logic: "Burn + Egg Sac", desc: "Explodes into burning fireworks." },
    { name: "Flash", ingredients: ["Light", "Lightning"], logic: "Light + Lightning", desc: "Screen-wide damage & blind." },
    { name: "Flicker", ingredients: ["Light", "Dark"], logic: "Light + Dark", desc: "Screen-wide tick damage." },
    { name: "Freeze Ray", ingredients: ["Freeze", "Laser (Horizontal)", "Laser (Vertical)"], logic: "Freeze + Laser (H or V)", desc: "Beam freezes enemies." },
    { name: "Frozen Flame", ingredients: ["Burn", "Freeze"], logic: "Burn + Freeze", desc: "Frostburn: DOT + Dmg Amp." },
    { name: "Glacier", ingredients: ["Freeze", "Earthquake", "Stone"], logic: "Freeze + (Earthquake OR Stone)", desc: "Leaves damaging spikes." },
    { name: "Hemorrhage", ingredients: ["Bleed", "Iron"], logic: "Bleed + Iron", desc: "Consumes bleed for % HP dmg." },
    { name: "Holy Laser", ingredients: ["Laser (Horizontal)", "Laser (Vertical)"], logic: "Laser(H) + Laser(V)", desc: "Cross laser damage." },
    { name: "Incubus", ingredients: ["Charm", "Dark"], logic: "Charm + Dark", desc: "Charmed enemies curse others." },
    { name: "Inferno", ingredients: ["Burn", "Wind"], logic: "Burn + Wind", desc: "AOE Burn aura." },
    { name: "Landslide", ingredients: ["Stone", "Earthquake"], logic: "Stone + Earthquake", desc: "Self-destructing AOE zone." },
    { name: "Laser Beam", ingredients: ["Light", "Laser (Horizontal)", "Laser (Vertical)"], logic: "Light + Laser (H or V)", desc: "High dmg beam + Blind." },
    { name: "Laser Cutter", ingredients: ["Steel", "Laser (Horizontal)", "Laser (Vertical)"], logic: "Steel + Laser (H or V)", desc: "Constant frontal laser." },
    { name: "Leech", ingredients: ["Brood Mother", "Bleed"], logic: "Brood Mother + Bleed", desc: "Leeches apply heavy bleed." },
    { name: "Lightning Rod", ingredients: ["Lightning", "Iron"], logic: "Lightning + Iron", desc: "Strikes attached enemies." },
    { name: "Lovestruck", ingredients: ["Charm", "Light", "Lightning"], logic: "Charm + (Light OR Lightning)", desc: "Enemies heal you." },
    { name: "Maggot", ingredients: ["Cell", "Brood Mother"], logic: "Cell + Brood Mother", desc: "Infests enemies, spawns babies." },
    { name: "Magma", ingredients: ["Burn", "Earthquake"], logic: "Burn + Earthquake", desc: "Leaves lava blobs." },
    { name: "Mosquito King", ingredients: ["Vampire", "Brood Mother"], logic: "Vampire + Brood Mother", desc: "Spawns high dmg mosquitoes." },
    { name: "Mosquito Swarm", ingredients: ["Vampire", "Egg Sac"], logic: "Vampire + Egg Sac", desc: "Explodes into mosquitoes." },
    { name: "Nosferatu", ingredients: ["Vampire Lord", "Mosquito King", "Spider Queen"], logic: "Vamp Lord + Mosq King + Spider Queen", desc: "Spawns bats -> Lords." },
    { name: "Noxious", ingredients: ["Wind", "Poison", "Dark"], logic: "Wind + (Poison OR Dark)", desc: "Passes through, AOE poison." },
    { name: "Nuclear Bomb", ingredients: ["Bomb", "Poison"], logic: "Bomb + Poison", desc: "Huge dmg + Radiation." },
    { name: "Overgrowth", ingredients: ["Earthquake", "Cell"], logic: "Earthquake + Cell", desc: "Stacking burst AOE." },
    { name: "Phantom", ingredients: ["Ghost", "Dark"], logic: "Ghost + Dark", desc: "Curses enemies." },
    { name: "Radiation Beam", ingredients: ["Laser (Horizontal)", "Laser (Vertical)", "Poison", "Cell"], logic: "Laser (H/V) + (Poison OR Cell)", desc: "Beam applies Radiation." },
    { name: "Sacrifice", ingredients: ["Bleed", "Dark"], logic: "Bleed + Dark", desc: "Heavy bleed + Curse." },
    { name: "Sandstorm", ingredients: ["Wind", "Earthquake", "Stone"], logic: "Wind + (Earthquake OR Stone)", desc: "Storm aura + Blind." },
    { name: "Satan", ingredients: ["Incubus", "Succubus"], logic: "Incubus + Succubus", desc: "Global Burn + Berserk." },
    { name: "Shotgun", ingredients: ["Iron", "Egg Sac"], logic: "Iron + Egg Sac", desc: "Shoots iron baby balls." },
    { name: "Soul Sucker", ingredients: ["Ghost", "Vampire"], logic: "Ghost + Vampire", desc: "Saps HP and Attack." },
    { name: "Spider Queen", ingredients: ["Brood Mother", "Egg Sac"], logic: "Brood Mother + Egg Sac", desc: "Spawns Egg Sacs." },
    { name: "Steel", ingredients: ["Iron", "Stone"], logic: "Iron + Stone", desc: "Slow, dmg ramps up." },
    { name: "Storm", ingredients: ["Lightning", "Wind"], logic: "Lightning + Wind", desc: "Periodic lightning strikes." },
    { name: "Succubus", ingredients: ["Charm", "Vampire"], logic: "Charm + Vampire", desc: "Charm + Heal on hit." },
    { name: "Sun", ingredients: ["Light", "Burn"], logic: "Light + Burn", desc: "Global Blind + Burn." },
    { name: "Swamp", ingredients: ["Poison", "Earthquake"], logic: "Poison + Earthquake", desc: "Tar blobs: Slow + Poison." },
    { name: "Vampire Lord", ingredients: ["Vampire", "Bleed", "Dark"], logic: "Vampire + (Bleed OR Dark)", desc: "Heals and consumes bleed." },
    { name: "Virus", ingredients: ["Poison", "Ghost", "Cell"], logic: "Poison + (Ghost OR Cell)", desc: "Spreading disease." },
    { name: "Voluptuous Egg Sac", ingredients: ["Egg Sac", "Cell"], logic: "Egg Sac + Cell", desc: "Explodes into MORE egg sacs." },
    { name: "Wraith", ingredients: ["Freeze", "Ghost"], logic: "Freeze + Ghost", desc: "Freezes passed enemies." }
];

export const passiveEvolutions = [
    { name: "Cornucopia", ingredients: ["Baby Rattle", "War Horn"], logic: "Baby Rattle + War Horn", desc: "Extra baby balls." },
    { name: "Deadeye's Cross", ingredients: ["Sapphire Hilted Dagger", "Ruby Hilted Dagger", "Diamond Hilted Dagger", "Emerald Hilted Dagger"], logic: "4x Daggers", desc: "60% Crit Chance." },
    { name: "Deadeye's Impaler", ingredients: ["Deadeye's Cross", "Gracious Impaler"], logic: "Deadeye's Cross + Gracious Impaler", desc: "Crit kills non-bosses." },
    { name: "Gracious Impaler", ingredients: ["Reacher's Spear", "Deadeye's Amulet"], logic: "Reacher's Spear + Deadeye's Amulet", desc: "Crit kills instantly." },
    { name: "Grotesque Artillery", ingredients: ["Turret", "Hand Fan"], logic: "Turret + Hand Fan", desc: "Shoots random special balls." },
    { name: "Odiferous Shell", ingredients: ["Wretched Onion", "Breastplate"], logic: "Wretched Onion + Breastplate", desc: "Contact has 50% kill chance." },
    { name: "Phantom Regalia", ingredients: ["Ethereal Cloak", "Ghostly Corset"], logic: "Ethereal Cloak + Ghostly Corset", desc: "Balls pierce to back wall." },
    { name: "Soul Reaver", ingredients: ["Everflowing Goblet", "Vampiric Sword"], logic: "Everflowing Goblet + Vampiric Sword", desc: "Overheal past max HP." },
    { name: "Tormenters Mask", ingredients: ["Spiked Collar", "Crown of Thorns"], logic: "Spiked Collar + Crown of Thorns", desc: "Enemies die on detection (10%)." },
    { name: "Wings of the Anointed", ingredients: ["Radiant Feather", "Fleet Feet"], logic: "Radiant Feather + Fleet Feet", desc: "Speed up + Hazard immunity." }
];
